spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://172.20.10.9:5432/spring_test
    username: postgres
    password: postgres
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB
