version: '3.8'
# networks:
#   spring-postgres-networks:
#     driver: bridge
volumes:
  postgres_db:
services:
  # backend_spring:
  #   container_name: backend_spring
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - spring-postgres-networks
  #   depends_on:
  #     - postgres
  postgres:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spring_test
    # networks:
    #   - spring-postgres-networks
    restart: always
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    # networks:
    #   - spring-postgres-networks
    # depends_on:
    #   - postgres